### ISSUE TITLE
Errors Field is missing at HomeStatusBody

### ISSUE THREAD

**Issue by notz** [navybk/netatmo-java-api#1]
According to the netatmo documentation their may be an errors field in the response json.

```
2018-12-03 18:08:03.024 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "errors" (class io.rudolph.netatmo.api.energy.model.HomeStatusBody), not marked as ignorable (one known property: "home"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 96] (through reference chain: io.rudolph.netatmo.api.energy.model.TypedBaseResult["body"]->io.rudolph.netatmo.api.energy.model.HomeStatusBody["errors"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1543) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:504) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203) ~[18:com.fasterxml.jackson.core.jackson-databind:2.4.5]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32) ~[?:?]
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23) ~[?:?]
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122) ~[?:?]
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217) ~[?:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[?:?]
        at io.rudolph.netatmo.executable.CallExecutable.executeSync(CallExecutable.kt:22) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoRoomHandler.updateChannels(NetatmoRoomHandler.java:107) ~[?:?]
```

**Comment by navybk** [comment]
Unfortunately the documentation in https://dev.netatmo.com/en-US/resources/technical/reference/energy/homestatus does not reflect the actual backend responses. A result will either include a data model or an error, I never experienced both. 
So the current changes will make all lib calls return an error object (even not a list like the doc states) if one exists.
